name: Generate Documentation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Doxygen and Graphviz
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz
        
    - name: Verify Doxygen installation
      run: |
        doxygen --version
        dot -V
        
    - name: Configure CMake for documentation
      run: |
        cmake -B build -DBUILD_DOCS=ON
        
    - name: Generate documentation
      run: |
        cmake --build build --target docs
        
    - name: Verify documentation was generated
      run: |
        echo "Checking if documentation was generated..."
        if [ -f "docs/html/index.html" ]; then
          echo "✅ Documentation found in docs/html/"
          ls -la docs/html/ | head -10
          echo "Total files: $(find docs/html -type f | wc -l)"
        else
          echo "❌ Documentation not found!"
          echo "Project root contents:"
          ls -la
          echo "Looking for any HTML files:"
          find . -name "*.html" -type f || echo "No HTML files found"
          exit 1
        fi
        
    - name: Setup Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/configure-pages@v4
      
    - name: Upload to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/html
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      id: deployment
      uses: actions/deploy-pages@v4
        
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/html/
        retention-days: 30